name: Atualizar dados CSV

on:
  schedule:
    - cron: '0 7 * * *'  # Executa diariamente às 7h da manhã (UTC)
  workflow_dispatch:     # Permite execução manual

jobs:
  atualizar-csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests

    - name: Executar script de atualização
      run: python atualizar_dados.py

    - name: Commit e push dos arquivos atualizados
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add tarifas_aneel.csv pld_ccee.csv
        git commit -m "Atualização automática dos dados CSV"
        git push
